spring.datasource.url=jdbc:sqlite:dev.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jackson.deserialization.UNWRAP_ROOT_VALUE=true

image.default=https://static.productionready.io/images/smiley-cyrus.jpg

jwt.secret=${JWT_SECRET:M4ElsFXvpmXRmp7o3h78jfNDNgQw+gVMQ0DMBZDCqxO2OS0HILtLYU1lQzL2PXdGVXRbyLk/Zu8ZeoRPE6qxSQ==}
jwt.sessionTime=3600

cors.allowed-origins=http://localhost:3000,http://localhost:4200

mybatis.configuration.cache-enabled=true
mybatis.configuration.default-statement-timeout=3000
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.type-handlers-package=io.spring.infrastructure.mybatis
mybatis.mapper-locations=mapper/*.xml

logging.level.io.spring.infrastructure.mybatis.readservice.ArticleReadService=DEBUG
logging.level.io.spring.infrastructure.mybatis.mapper=DEBUG
